### PR TITLE
Include authors

### PR DESCRIPTION
**Pull request by drewcimino**

### CODE REVIEW

**Comment by drewcimino** [comment]
Interesting that the commit history is there even though the repo is gone

**Comment by drewcimino** [comment]
How often do you think Github runs gc?

**Comment by PatrickTulskie** [comment]
@drewcimino probably never unless you request it

**Comment by drewcimino** [comment]
Even then: https://stackoverflow.com/questions/15261880/does-github-garbage-collect-dangling-commits-referenced-in-pull-requests

**Pull request closed without merging**
