### PR TITLE
Update to lita >= 4

### PR DESCRIPTION
**Pull request by jjasghar**
- Removed Gemfile.lock
- Updated the ping response
- Updated the Gemspec to a newer version

### CODE REVIEW

**Comment by PatrickTulskie** [comment]
I'll get this merged in later today.

You're not a fan of "PoNg pOnG PoNg pOnG"?

**Comment by PatrickTulskie** [comment]
Actually... now that I look at this again... the plugin will still technically work on Lita 2.  Why are you requiring version 4?

**Comment by jjasghar** [comment]
Yeah I personally think `Pong` is better. It's straight forward :metal: 

The Gem.lock file would only take that on my testing machine(s), i'm horrible about the Gem dependancies stuff, suggestions on how to get around it?

**Comment by PatrickTulskie** [comment]
Okay I figured out what happened...

I wrote this and then never pushed it to rubygems.  Someone else forked my repo, threw their name on it, and just pushed it without saying anything to me.  I updated my gemspec to work with >= 2.0 (I personally use a fork of Lita 3.0) and they never did that.

https://github.com/marceldegraaf/lita-ping/blob/master/lita-ping.gemspec

vs

https://github.com/PatrickTulskie/lita-ping/blob/master/lita-ping.gemspec

Even if I accepted your pull request I couldn't do anything about it because this other dude owns the gem on rubygems.org.  If you want to just use my original version in your Lita 4.0 app you can use this in your Gemfile:

```
gem "lita-ping", :git => "git@github.com:PatrickTulskie/lita-ping.git"
```

As for the other mess, I'm not really sure what to do yet.

**Comment by jjasghar** [comment]
Ah ok. So maybe if we ping @marceldegraaf and ask him to add you as a contrib to the gem on ruby gems we can get this merged in and pushed up? How about it @marceldegraaf? It seems we all more or less want the exact same thing we just have a logistical issue.

**Comment by marceldegraaf** [comment]
Hi @jjasghar and @PatrickTulskie, sorry for the inconvenience. I never realised I blocked an official version of the gem on Rubygems.

@PatrickTulskie let's transfer ownership of the gem to you. Do you use the GMail address in your Github profile on Rubygems as well? I'll add you as an owner of the gem, and I think you can remove my ownership after that (not sure how that works).

**Comment by PatrickTulskie** [comment]
@marceldegraaf No worries.  I've never had this happen before so I wasn't really sure of how to handle it.

Yeah the email address is one in the same.  I'll prepare an updated gem build later and push it up.  Thanks!

**Comment by jjasghar** [comment]
selfie-2

Stupid mirroring.

**Comment by marceldegraaf** [comment]
@PatrickTulskie you're an owner of the lita-ping gem on Rubygems now. Let me know if this works.

**Comment by PatrickTulskie** [comment]
Okay cool.  I guess I'll just rebase on yours, and then re-apply my gemspec updates and push a new version.  That should take care of the craziness.

**Comment by marceldegraaf** [comment]
Sure, go ahead, and feel free to remove me from the gem owners if you like (and if that's possible). I'm not using Lita anymore, so I don't plan on making any changes to this code.

**Comment by PatrickTulskie** [comment]
Awesome looks like we're all set.  I just pushed 1.0.2 which should work for all the Litas north of 2.  I'll close this out.  Everyone should be good to go now.

**Pull request closed without merging**
